require('dotenv').config();
const mongoose = require('mongoose');
const Seller = require('./models/Seller');
const Product = require('./models/Product');
const User = require('./models/User');

const sellers = [
  {
    name: 'Samarkand Home Goods',
    slug: 'samarkand-home-goods',
    logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200&h=200&fit=crop',
    experienceYears: 5,
    location: 'Samarqand',
    reliabilityScore: 94,
    responseTimeSeconds: 12,
    isVerified: true,
    description: 'Uy-ro\'zg\'or buyumlari va mebel mahsulotlari.',
  },
  {
    name: 'UzTech Electronics',
    slug: 'uztech-electronics',
    logoUrl: 'https://images.unsplash.com/photo-1565688534245-05d6b5be184a?w=200&h=200&fit=crop',
    experienceYears: 6,
    location: 'Toshkent',
    reliabilityScore: 98,
    responseTimeSeconds: 24,
    isVerified: true,
    description: 'Elektronika va smart qurilmalar.',
  },
  {
    name: 'Global Textile Group',
    slug: 'global-textile-group',
    logoUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=200&h=200&fit=crop',
    experienceYears: 10,
    location: 'Namangan',
    reliabilityScore: 100,
    responseTimeSeconds: 1,
    isVerified: true,
    description: 'Tekstil va kiyim-kechak mahsulotlari.',
  },
  {
    name: "Stroy-Market UZ",
    slug: 'stroy-market-uz',
    logoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop',
    experienceYears: 4,
    location: "Farg'ona",
    reliabilityScore: 95,
    responseTimeSeconds: 2,
    isVerified: true,
    description: 'Qurilish materiallari va asbob-uskunalar.',
  },
  {
    name: 'Smart Solutions',
    slug: 'smart-solutions',
    logoUrl: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=200&h=200&fit=crop',
    experienceYears: 2,
    location: 'Buxoro',
    reliabilityScore: 92,
    responseTimeSeconds: 4,
    isVerified: true,
    description: 'Smart uy texnikasi va IoT qurilmalar.',
  },
  {
    name: 'Andijon Agro Market',
    slug: 'andijon-agro-market',
    logoUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=200&h=200&fit=crop',
    experienceYears: 8,
    location: 'Andijon',
    reliabilityScore: 96,
    responseTimeSeconds: 8,
    isVerified: true,
    description: 'Qishloq xo\'jaligi mahsulotlari va urug\'lar.',
  },
  {
    name: 'Tashkent Beauty Shop',
    slug: 'tashkent-beauty-shop',
    logoUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&h=200&fit=crop',
    experienceYears: 3,
    location: 'Toshkent',
    reliabilityScore: 91,
    responseTimeSeconds: 15,
    isVerified: true,
    description: 'Kosmetika va parfyumeriya mahsulotlari.',
  },
  {
    name: 'Navoiy Sport Gear',
    slug: 'navoiy-sport-gear',
    logoUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607c79545?w=200&h=200&fit=crop',
    experienceYears: 7,
    location: 'Navoiy',
    reliabilityScore: 93,
    responseTimeSeconds: 6,
    isVerified: false,
    description: 'Sport jihozlari va kiyimlari.',
  },
  {
    name: 'Qarshi Mebel Uy',
    slug: 'qarshi-mebel-uy',
    logoUrl: 'https://images.unsplash.com/photo-1555041469-a586c64ea9bc?w=200&h=200&fit=crop',
    experienceYears: 12,
    location: 'Qarshi',
    reliabilityScore: 97,
    responseTimeSeconds: 3,
    isVerified: true,
    description: 'Ofis va uy mebellari.',
  },
  {
    name: 'Silk Road Foods',
    slug: 'silk-road-foods',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&h=200&fit=crop',
    experienceYears: 5,
    location: 'Toshkent',
    reliabilityScore: 89,
    responseTimeSeconds: 18,
    isVerified: false,
    description: 'Oziq-ovqat va quruq mevalar.',
  },
];

const products = [
  // Oyoq kiyim
  {
    name: 'Ayollar sport krossovkasi (yengil)',
    slug: 'ayollar-sport-krossovkasi-yengil',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    price: 399000,
    discountPercent: 8,
    minOrderQuantity: 8,
    category: 'Oyoq kiyim',
    isTop: true,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Erkaklar sport krossovkasi',
    slug: 'erkaklar-sport-krossovkasi',
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0a29cbf1f4b3?w=400&h=400&fit=crop',
    price: 450000,
    discountPercent: 0,
    minOrderQuantity: 6,
    category: 'Oyoq kiyim',
    isTop: true,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Bolalar sport krossovkasi',
    slug: 'bolalar-sport-krossovkasi',
    imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=400&fit=crop',
    price: 280000,
    discountPercent: 20,
    minOrderQuantity: 12,
    category: 'Oyoq kiyim',
    isTop: true,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Ayollar baland poshna tufli',
    slug: 'ayollar-baland-poshna-tufli',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd1?w=400&h=400&fit=crop',
    price: 520000,
    discountPercent: 12,
    minOrderQuantity: 6,
    category: 'Oyoq kiyim',
    isTop: true,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Erkaklar klassik tufli (qora)',
    slug: 'erkaklar-klassik-tufli-qora',
    imageUrl: 'https://images.unsplash.com/photo-1614252239476-3dfea0772e49?w=400&h=400&fit=crop',
    price: 680000,
    discountPercent: 0,
    minOrderQuantity: 4,
    category: 'Oyoq kiyim',
    isTop: false,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Yozgi sandallar (uniseks)',
    slug: 'yozgi-sandallar-uniseks',
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-416a7a364351?w=400&h=400&fit=crop',
    price: 195000,
    discountPercent: 5,
    minOrderQuantity: 10,
    category: 'Oyoq kiyim',
    isTop: false,
    sellerSlug: 'navoiy-sport-gear',
  },

  // Maishiy texnika
  {
    name: 'Multivarka 5L (avtomatik)',
    slug: 'multivarka-5l-avtomatik',
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop',
    price: 890000,
    discountPercent: 5,
    minOrderQuantity: 4,
    category: 'Maishiy texnika',
    isTop: true,
    sellerSlug: 'samarkand-home-goods',
  },
  {
    name: 'Blender va mikser to\'plami',
    slug: 'blender-va-mikser-toplami',
    imageUrl: 'https://images.unsplash.com/photo-1570222094114-d054a817e562?w=400&h=400&fit=crop',
    price: 520000,
    discountPercent: 0,
    minOrderQuantity: 6,
    category: 'Maishiy texnika',
    isTop: true,
    sellerSlug: 'samarkand-home-goods',
  },
  {
    name: 'Kir yuvish mashinasi (7kg)',
    slug: 'kir-yuvish-mashinasi-7kg',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=400&h=400&fit=crop',
    price: 4500000,
    discountPercent: 7,
    minOrderQuantity: 2,
    category: 'Maishiy texnika',
    isTop: true,
    sellerSlug: 'samarkand-home-goods',
  },
  {
    name: 'Mikroto\'lqinli pech (25L)',
    slug: 'mikrotolqinli-pech-25l',
    imageUrl: 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=400&h=400&fit=crop',
    price: 1200000,
    discountPercent: 0,
    minOrderQuantity: 3,
    category: 'Maishiy texnika',
    isTop: false,
    sellerSlug: 'samarkand-home-goods',
  },
  {
    name: 'Changyutgich (2000W)',
    slug: 'changyutgich-2000w',
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=400&fit=crop',
    price: 650000,
    discountPercent: 10,
    minOrderQuantity: 5,
    category: 'Maishiy texnika',
    isTop: false,
    sellerSlug: 'samarkand-home-goods',
  },
  {
    name: 'Elektr choynak (1.7L, shisha)',
    slug: 'elektr-choynak-17l-shisha',
    imageUrl: 'https://images.unsplash.com/photo-1591789197733-85c8a0a4972b?w=400&h=400&fit=crop',
    price: 185000,
    discountPercent: 0,
    minOrderQuantity: 12,
    category: 'Maishiy texnika',
    isTop: false,
    sellerSlug: 'samarkand-home-goods',
  },

  // Elektronika
  {
    name: 'Smartfon (128GB, 5G)',
    slug: 'smartfon-128gb-5g',
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop',
    price: 3200000,
    discountPercent: 10,
    minOrderQuantity: 3,
    category: 'Elektronika',
    isTop: true,
    sellerSlug: 'uztech-electronics',
  },
  {
    name: 'Naushnik (simli, mikrofonli)',
    slug: 'naushnik-simli-mikrofonli',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    price: 185000,
    discountPercent: 0,
    minOrderQuantity: 15,
    category: 'Elektronika',
    isTop: true,
    sellerSlug: 'uztech-electronics',
  },
  {
    name: 'Noutbuk (15.6", 16GB RAM)',
    slug: 'noutbuk-156-16gb-ram',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop',
    price: 8500000,
    discountPercent: 5,
    minOrderQuantity: 2,
    category: 'Elektronika',
    isTop: true,
    sellerSlug: 'uztech-electronics',
  },
  {
    name: 'Planshet (10", Wi-Fi)',
    slug: 'planshet-10-wifi',
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop',
    price: 2800000,
    discountPercent: 8,
    minOrderQuantity: 3,
    category: 'Elektronika',
    isTop: true,
    sellerSlug: 'uztech-electronics',
  },
  {
    name: 'Simsiz naushnik (TWS)',
    slug: 'simsiz-naushnik-tws',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
    price: 320000,
    discountPercent: 15,
    minOrderQuantity: 10,
    category: 'Elektronika',
    isTop: false,
    sellerSlug: 'uztech-electronics',
  },
  {
    name: 'Smart soat (sport)',
    slug: 'smart-soat-sport',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    price: 890000,
    discountPercent: 0,
    minOrderQuantity: 5,
    category: 'Elektronika',
    isTop: false,
    sellerSlug: 'uztech-electronics',
  },
  {
    name: 'Portativ kolonka (Bluetooth)',
    slug: 'portativ-kolonka-bluetooth',
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    price: 450000,
    discountPercent: 12,
    minOrderQuantity: 8,
    category: 'Elektronika',
    isTop: false,
    sellerSlug: 'smart-solutions',
  },
  {
    name: 'Smart uy sensori (Wi-Fi)',
    slug: 'smart-uy-sensori-wifi',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400&h=400&fit=crop',
    price: 210000,
    discountPercent: 0,
    minOrderQuantity: 10,
    category: 'Elektronika',
    isTop: true,
    sellerSlug: 'smart-solutions',
  },
  {
    name: 'Wi-Fi router (dual band)',
    slug: 'wifi-router-dual-band',
    imageUrl: 'https://images.unsplash.com/photo-1606904820313-f991a61545f5?w=400&h=400&fit=crop',
    price: 580000,
    discountPercent: 0,
    minOrderQuantity: 6,
    category: 'Elektronika',
    isTop: false,
    sellerSlug: 'smart-solutions',
  },

  // Kiyim
  {
    name: 'Erkaklar ko\'ylagi (ofis)',
    slug: 'erkaklar-koylagi-ofis',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b00?w=400&h=400&fit=crop',
    price: 220000,
    discountPercent: 0,
    minOrderQuantity: 10,
    category: 'Kiyim',
    isTop: false,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Ayollar libos (yozgi)',
    slug: 'ayollar-libos-yozgi',
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
    price: 350000,
    discountPercent: 18,
    minOrderQuantity: 8,
    category: 'Kiyim',
    isTop: true,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Bolalar kurtka (qishki)',
    slug: 'bolalar-kurtka-qishki',
    imageUrl: 'https://images.unsplash.com/photo-1519238263530-99bdd5db86df?w=400&h=400&fit=crop',
    price: 420000,
    discountPercent: 10,
    minOrderQuantity: 6,
    category: 'Kiyim',
    isTop: false,
    sellerSlug: 'global-textile-group',
  },
  {
    name: 'Sport kostyum to\'plami',
    slug: 'sport-kostyum-toplami',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=400&fit=crop',
    price: 480000,
    discountPercent: 0,
    minOrderQuantity: 8,
    category: 'Kiyim',
    isTop: false,
    sellerSlug: 'navoiy-sport-gear',
  },

  // Mebel
  {
    name: 'Ofis stuli (ergonomik)',
    slug: 'ofis-stuli-ergonomik',
    imageUrl: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&h=400&fit=crop',
    price: 1850000,
    discountPercent: 0,
    minOrderQuantity: 3,
    category: 'Mebel',
    isTop: true,
    sellerSlug: 'qarshi-mebel-uy',
  },
  {
    name: 'Yotoq stoli va shkaf to\'plami',
    slug: 'yotoq-stoli-va-shkaf-toplami',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c64ea9bc?w=400&h=400&fit=crop',
    price: 5200000,
    discountPercent: 5,
    minOrderQuantity: 1,
    category: 'Mebel',
    isTop: true,
    sellerSlug: 'qarshi-mebel-uy',
  },
  {
    name: 'Divan (3 o\'rinli, mato)',
    slug: 'divan-3-orinli-mato',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c64ea9bc?w=400&h=400&fit=crop',
    price: 6800000,
    discountPercent: 0,
    minOrderQuantity: 1,
    category: 'Mebel',
    isTop: false,
    sellerSlug: 'qarshi-mebel-uy',
  },
  {
    name: 'Oshxona stoli (6 o\'rinli)',
    slug: 'oshxona-stoli-6-orinli',
    imageUrl: 'https://images.unsplash.com/photo-1617806118773-1e0a14a6ec50?w=400&h=400&fit=crop',
    price: 3200000,
    discountPercent: 0,
    minOrderQuantity: 2,
    category: 'Mebel',
    isTop: false,
    sellerSlug: 'qarshi-mebel-uy',
  },

  // Qurilish
  {
    name: 'Qurilish asboblari to\'plami',
    slug: 'qurilish-asboblari-toplami',
    imageUrl: 'https://images.unsplash.com/photo-1581147036320-c1c89f0a5745?w=400&h=400&fit=crop',
    price: 750000,
    discountPercent: 0,
    minOrderQuantity: 5,
    category: 'Qurilish',
    isTop: true,
    sellerSlug: 'stroy-market-uz',
  },
  {
    name: 'Elektr drill (akkumulyatorli)',
    slug: 'elektr-drill-akkumulyatorli',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=400&fit=crop',
    price: 890000,
    discountPercent: 8,
    minOrderQuantity: 4,
    category: 'Qurilish',
    isTop: false,
    sellerSlug: 'stroy-market-uz',
  },
  {
    name: 'Sement (50kg, M400)',
    slug: 'sement-50kg-m400',
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&h=400&fit=crop',
    price: 85000,
    discountPercent: 0,
    minOrderQuantity: 50,
    category: 'Qurilish',
    isTop: false,
    sellerSlug: 'stroy-market-uz',
  },
  {
    name: 'Bo\'yoq (ichki, 10L)',
    slug: 'boyoq-ichki-10l',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&h=400&fit=crop',
    price: 320000,
    discountPercent: 0,
    minOrderQuantity: 10,
    category: 'Qurilish',
    isTop: false,
    sellerSlug: 'stroy-market-uz',
  },

  // O'yinchoqlar
  {
    name: 'Bolalar o\'yinchoq to\'plami',
    slug: 'bolalar-oyinchoq-toplami',
    imageUrl: 'https://images.unsplash.com/photo-1558066285-4f8d7a683642?w=400&h=400&fit=crop',
    price: 95000,
    discountPercent: 15,
    minOrderQuantity: 20,
    category: 'O\'yinchoqlar',
    isTop: true,
    sellerSlug: 'smart-solutions',
  },
  {
    name: 'LEGO konstruktor (500 dona)',
    slug: 'lego-konstruktor-500-dona',
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop',
    price: 280000,
    discountPercent: 0,
    minOrderQuantity: 10,
    category: 'O\'yinchoqlar',
    isTop: false,
    sellerSlug: 'smart-solutions',
  },
  {
    name: 'Remote control mashina',
    slug: 'remote-control-mashina',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    price: 165000,
    discountPercent: 10,
    minOrderQuantity: 12,
    category: 'O\'yinchoqlar',
    isTop: false,
    sellerSlug: 'smart-solutions',
  },

  // Kosmetika
  {
    name: 'Terini parvarish to\'plami',
    slug: 'terini-parvarish-toplami',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
    price: 380000,
    discountPercent: 12,
    minOrderQuantity: 6,
    category: 'Kosmetika',
    isTop: true,
    sellerSlug: 'tashkent-beauty-shop',
  },
  {
    name: 'Parfyum (50ml, erkaklar)',
    slug: 'parfyum-50ml-erkaklar',
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop',
    price: 520000,
    discountPercent: 0,
    minOrderQuantity: 5,
    category: 'Kosmetika',
    isTop: false,
    sellerSlug: 'tashkent-beauty-shop',
  },
  {
    name: 'Soch parvarish to\'plami',
    slug: 'soch-parvarish-toplami',
    imageUrl: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    price: 245000,
    discountPercent: 0,
    minOrderQuantity: 8,
    category: 'Kosmetika',
    isTop: false,
    sellerSlug: 'tashkent-beauty-shop',
  },

  // Oziq-ovqat
  {
    name: 'Quruq meva aralashmasi (1kg)',
    slug: 'quruq-meva-aralashmasi-1kg',
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
    price: 95000,
    discountPercent: 0,
    minOrderQuantity: 30,
    category: 'Oziq-ovqat',
    isTop: false,
    sellerSlug: 'silk-road-foods',
  },
  {
    name: 'Yong\'oq aralashmasi (500g)',
    slug: 'yongq-aralashmasi-500g',
    imageUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
    price: 78000,
    discountPercent: 5,
    minOrderQuantity: 25,
    category: 'Oziq-ovqat',
    isTop: false,
    sellerSlug: 'silk-road-foods',
  },
  {
    name: 'Asal (tabiiy, 1kg)',
    slug: 'asal-tabiiy-1kg',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop',
    price: 120000,
    discountPercent: 0,
    minOrderQuantity: 20,
    category: 'Oziq-ovqat',
    isTop: true,
    sellerSlug: 'andijon-agro-market',
  },
  {
    name: 'Pomidor urug\'i (1kg)',
    slug: 'pomidor-urugi-1kg',
    imageUrl: 'https://images.unsplash.com/photo-1592924357238-91a4daadc663?w=400&h=400&fit=crop',
    price: 45000,
    discountPercent: 0,
    minOrderQuantity: 50,
    category: 'Oziq-ovqat',
    isTop: false,
    sellerSlug: 'andijon-agro-market',
  },

  // Sport
  {
    name: 'Yoga gilamchasi (6mm)',
    slug: 'yoga-gilamchasi-6mm',
    imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    price: 125000,
    discountPercent: 0,
    minOrderQuantity: 15,
    category: 'Sport',
    isTop: false,
    sellerSlug: 'navoiy-sport-gear',
  },
  {
    name: 'Dumbbell to\'plami (20kg)',
    slug: 'dumbbell-toplami-20kg',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
    price: 980000,
    discountPercent: 8,
    minOrderQuantity: 3,
    category: 'Sport',
    isTop: true,
    sellerSlug: 'navoiy-sport-gear',
  },
  {
    name: 'Futbol to\'pi (professional)',
    slug: 'futbol-topi-professional',
    imageUrl: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=400&h=400&fit=crop',
    price: 185000,
    discountPercent: 0,
    minOrderQuantity: 10,
    category: 'Sport',
    isTop: false,
    sellerSlug: 'navoiy-sport-gear',
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('MongoDB ulandi');

    await Promise.all([
      Seller.deleteMany(),
      Product.deleteMany(),
      User.deleteMany(),
    ]);
    console.log('Eski ma\'lumotlar o\'chirildi');

    const createdSellers = await Seller.insertMany(sellers);
    const sellerMap = Object.fromEntries(
      createdSellers.map((s) => [s.slug, s._id])
    );

    const productsWithSellers = products.map(({ sellerSlug, ...product }) => ({
      ...product,
      seller: sellerMap[sellerSlug],
    }));

    await Product.insertMany(productsWithSellers);
    console.log(`${createdSellers.length} ta sotuvchi va ${products.length} ta mahsulot qo'shildi`);

    await User.create({
      name: 'Test Foydalanuvchi',
      email: 'test@minibaba.uz',
      password: '123456',
    });
    console.log('Test foydalanuvchi yaratildi: test@minibaba.uz / 123456');

    process.exit(0);
  } catch (error) {
    console.error('Seed xatosi:', error.message);
    process.exit(1);
  }
};

seed();
